#!/bin/sh -f
# the next line restarts using wish \
exec wish "$0" "$@"
#!/local/TclTk8.0/bin/tclsh8.0
# 
# A more flexible startup mechanism is below, but it
# assumes you have tclsh in your path
#!/bin/sh -f
# the next line restarts using wish \
exec tclsh "$0" "$@"

#==============================================================
# Global Variables
#==============================================================

#==============================================================
#==============================================================
# Main program
#==============================================================
#==============================================================

set Damage 0
set Direction 0
set Fuel   1000

#set LogF [open "log.[pid]" w]
#set LogF [open "/dev/null" w]
#set LogF stderr

#puts $LogF "Command line: ([lindex $argv 0] [lindex $argv 1])"
set done 0
#puts $LogF "1: starting"
set dirchange 5
set nodirchange 0
while {!$done} {
   gets stdin statline
   gets stdin scanline
   #puts $LogF "Controller: ($statline) ($scanline)"
   #flush $LogF
   regexp {([0-9]*) ([0-9]*) ([0-9]*) ([0-9]*) ([0-9]*) ([0-9]*) ([0-9]*)} \
           $statline  dummy xpos ypos direction velocity fuel damage damagetype
   regexp {([01]) (.*)} $scanline dummy scanflag scanresults
   if {$damage > 0} {
      # then handle damage type
   }
   set action scan
   if {$scanflag > 0} {
      regexp {([0-9]*) (\-?[0-9\.]*) ([0-9\.]*) ([0-9\.]*)} $scanresults dummy\
              objectid posangle distance dirangle
      if {$objectid == 2} {
         if {$distance < 100} {
            set action fire
         }
         #set difa [expr $direction - $dirangle]
         set difa $posangle
         set dirchange [expr round($posangle/(-1+(-4*((301.0-$distance)/301))))]
         if {0} {
         if {$difa < 0} {
            set difa [expr 360 - $difa]
         }
         if {$difa < 180} {
            set dirchange [expr ($difa/20.0 + 1)]
         } else { 
            set dirchange [expr (360-$difa)/5.0 + 1]
         }
         set nodirchange 0
         }
      }
   }
   puts "[expr round($dirchange)] 0"
   puts "$action"
   flush stdout
   incr nodirchange
   if {$nodirchange > 200} {
      set nodirchange 0
      set dirchange [expr round(rand()*32432)%10]
   }
}
